base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register, name='register'),
]

pacility/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('', include('homepage.urls')),
    path('report_form/', include('report_form.urls')),
    path('report_list/', include('report_list.urls')),
    path('testimony/', include('testimony.urls')),
]

testimony/urls.py
from django.urls import path
from . import views

app_name = 'testimony'

urlpatterns = [
	path('', views.testimony, name='testimony'),
	path('add_testimony/', views.add_testimony, name="add_testimony"),
	path('getTestimonyJson/', views.getTestimonyJson, name="getTestimonyJson"),
]

testimony/models.py
from django.db import models

class Testimony(models.Model):
	username = models.CharField(max_length = 20)
	title = models.CharField(max_length = 50)
	content = models.TextField()
	
	def __str__(self):
		return f"{self.title}"

testimony/forms.py
from django import forms

class TestimonyForm(forms.Form):
	username_attrs = {
		'placeholder': 'Username',
		'class': 'form-control',
		'readonly' : 'readonly',
	}

	title_attrs = {
		'placeholder': 'Title',
		'class': 'form-control',
	}

	content_attrs = {
		'placeholder': 'Write your testimony here...',
		'class': 'form-control',
		'rows': 5,
	}

	username = forms.CharField(label='', max_length = 20, widget = forms.TextInput(attrs = username_attrs))
	title = forms.CharField(label='', max_length = 50, widget = forms.TextInput(attrs = title_attrs))
	content = forms.CharField(label='', widget = forms.Textarea(attrs = content_attrs))

testimony/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TestimonyForm
from .models import Testimony
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.core import serializers
import json

def testimony(request):
        form = TestimonyForm(initial={'username' : request.user.username})
        testimony = Testimony.objects.all()        
        if request.user.is_authenticated:
                return render(request, 'testimonyUser.html', {'form': form })
        else :
                return render(request, 'testimony.html')
        
def add_testimony(request):
        if request.user.is_authenticated :
                if request.method == 'POST':
                        form = TestimonyForm(request.POST)
                        if form.is_valid():
                                username = request.user.username
                                title = form.cleaned_data['title']
                                content = form.cleaned_data['content']
                                
                                testimony = Testimony(username = username, title = title, content = content)
                                testimony.save()

        return HttpResponseRedirect(reverse('testimony:testimony'))

def getTestimonyJson(request) :
        testimonyJson = serializers.serialize('json', Testimony.objects.all())

        #testimonyJson3 = DictModelAdaptor(Testimony)
        testimonyJson4 = json.loads(serializers.serialize('json',Testimony.objects.all()))
        return JsonResponse({'testimony' : testimonyJson4}, safe=False)  

testimony/templates/testimony.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/testimony_style.css' %}">
	<script src="{% static 'js/testimonyJS.js' %}"></script>
{% endblock %}

{% block title %}Testimony{% endblock %}

{% block body %}
	{% include 'base/navbar.html' %}
	
	<div class="content-div">
		<h1 class="section-title text-center">TESTIMONY</h1>
		
		<!--button refresh-->
		<button method="POST" onclick="refresh()" type="button" class="btn btn-primary">Refresh</button>
		<div class="testimony_list"id="testimonyShow">

		</div>
	</div>


	{% include 'base/footer.html' %}
{% endblock %}

testimony/templates/testimonyUser.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/testimony_style.css' %}">
	<script src="{% static 'js/testimonyJS.js' %}"></script>
{% endblock %}

{% block title %}Testimony{% endblock %}

{% block body %}
	{% include 'base/navbar.html' %}
	
	<div class="content-div">
		<h1 class="section-title text-center">TESTIMONY</h1>
		<button href="#testimony-form" class="form-group btn-submit" data-toggle="collapse">Testify</button>
		<div class="collapse in" id="testimony-form">
			<form action="{% url 'testimony:add_testimony' %}" method="POST">
				{% csrf_token %}

				<div class="form-row">
					<div class="form-group col-sm-4">
						{{ form.username }}
					</div>
					<div class="form-group col-sm-8">
						{{ form.title }}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-sm-12">
						{{ form.content }}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-sm-12">
						<input class="form-group btn-submit float-right" type="submit" value="Post">
					</div>
				</div>		
			</form>
		</div>

		<!--button refresh-->
		<br>
		<button method="POST" onclick="refresh()" type="button" class="btn btn-primary">Refresh</button>
		<div class="testimony_list"id="testimonyShow">
		</div>
	</div>


	{% include 'base/footer.html' %}
{% endblock %}