base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register, name='register'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('add_announcement', views.add_announcement, name='add_announcement'),
	path('get_announcements', views.get_announcements, name='get_announcements'),
]

pacility/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('', include('homepage.urls')),
    path('report_form/', include('report_form.urls')),
    path('report_list/', include('report_list.urls')),
    path('testimony/', include('testimony.urls')),
]

homepage/models.py
from django.db import models

class Announcement(models.Model):
	username = models.CharField(max_length = 20)
	initial = models.CharField(max_length = 1)
	title = models.CharField(max_length = 50)
	content = models.TextField()
	date = models.CharField(max_length = 30)
	time = models.CharField(max_length = 5)

	def is_valid_announcement(self):
		username_valid = len(self.username) > 0 and len(self.username) < 21
		initial_valid = self.initial == self.username[:1].upper()
		title_valid = len(self.title) > 0 and len(self.title) < 51
		content_valid = len(self.content) > 0

		return username_valid and initial_valid and title_valid and content_valid

	
	def __str__(self):
		return f"{self.date} - {self.title}"

homepage/forms.py
from django import forms

class AnnouncementForm(forms.Form):
	username_attrs = {
		'placeholder': 'Username',
		'class': 'form-control',
	}

	title_attrs = {
		'placeholder': 'Title',
		'class': 'form-control',
	}

	content_attrs = {
		'placeholder': 'Write your post here...',
		'class': 'form-control',
		'rows': 5,
	}

	username = forms.CharField(label='', max_length = 20, widget = forms.TextInput(attrs = username_attrs))
	title = forms.CharField(label='', max_length = 50, widget = forms.TextInput(attrs = title_attrs))
	content = forms.CharField(label='', widget = forms.Textarea(attrs = content_attrs))

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import AnnouncementForm
from .models import Announcement
from datetime import datetime, timedelta
from django.http.response import JsonResponse

def index(request):
	context = {
		"form": AnnouncementForm(),
		"announcements": Announcement.objects.all()
	}

	return render(request, 'homepage/homepage.html', context)

def add_announcement(request):
	if request.method == 'POST':
		form = AnnouncementForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			initial = username[:1].upper()
			title = form.cleaned_data['title']
			content = form.cleaned_data['content']

			now = datetime.now() + timedelta(hours=7)
			day = now.strftime("%A")
			date = now.strftime("%e")
			month = now.strftime("%B")
			year = now.strftime("%Y")
			hour = now.strftime("%H")
			minute = now.strftime("%M")
			fulldate = f"{day}, {date} {month} {year}"
			time = f"{hour}:{minute} WIB"

			announcement = Announcement(username = username, initial = initial, title = title, content = content, date = fulldate, time = time)
			announcement.save()

	return HttpResponseRedirect(reverse('homepage:index'))

def get_announcements(request):
	announcements = Announcement.objects.all().values()
	announcement_dict = {'announcements': list(announcements)}
	return JsonResponse(announcement_dict, safe=False)

homepage/templates/homepage/homepage.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/home_style.css' %}">
	<script type="text/javascript" src="{% static 'homepage/homepage.js' %}"></script>
{% endblock %}

{% block title %}
	Home
{% endblock %}

{% block body %}
	{% include 'base/navbar.html' %}

	<div id="brand-div" class="flex-center">
		<div class="text-center">
			<p id="brand-title">pacility.</p>
			<p id="brand-description">a reporting web</p>
		</div>
	</div>

	<div class="content-div">
		<p class="section-title">ANNOUNCEMENTS</p>

		{% if user.is_authenticated %}
		<form action="{% url 'homepage:add_announcement' %}" id="announcement-form">
			{% csrf_token %}

			<input id="username" type="hidden" value="{{ user.username }}">
			<div class="form-row">
				<div class="form-group col-sm-4">
					{{ form.username }}
				</div>
				<div class="form-group col-sm-8">
					{{ form.title }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-sm-12">
					{{ form.content }}
				</div>
			</div>
			<div class="form-row">
				<div class="form-group col-sm-12">
					<input class="form-group btn-submit float-right" type="submit" value="Post">
				</div>
			</div>		
		</form>
		{% endif %}

		<div class="announcement-list">
		
		</div>
	</div>


	{% include 'base/footer.html' %}
{% endblock %}