base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register, name='register'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('add_announcement', views.add_announcement, name='add_announcement'),
	path('get_announcements', views.get_announcements, name='get_announcements'),
]

pacility/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('', include('homepage.urls')),
    path('report_form/', include('report_form.urls')),
    path('report_list/', include('report_list.urls')),
    path('testimony/', include('testimony.urls')),
]

report_form/urls.py
from django.urls import path
from . import views

app_name = 'report_form'

urlpatterns = [
	path('', views.add_report, name= 'report_form'),
	path('report_service/', views.add_report_service, name= 'add_report_service'),

]

report_list/urls.py
from django.urls import path
from . import views

app_name='report_list'

urlpatterns = [
	path('', views.report_list, name= 'report_list'),
	# path('', views.add_report, name= 'add_report_form'),
]

testimony/urls.py
from django.urls import path
from . import views

app_name = 'testimony'

urlpatterns = [
	path('', views.testimony, name='testimony'),
	path('add_testimony/', views.add_testimony, name="add_testimony"),
	path('getTestimonyJson/', views.getTestimonyJson, name="getTestimonyJson"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def login_view(request):
	if request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"]
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return HttpResponse('Success')
		return HttpResponse('Not Found')

	return HttpResponseRedirect(reverse('homepage:index'))

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('homepage:index'))

def register(request):
	if request.method == "POST":
		first_name = request.POST["first_name"]
		last_name = request.POST["last_name"]
		username = request.POST["username"]
		email = request.POST["email"]
		password = request.POST["password"]
		new_user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
		new_user.save()

		user = authenticate(request, username=username, password=password)
		login(request, user)
		return HttpResponseRedirect(reverse('homepage:index'))

	return HttpResponseRedirect(reverse('homepage:index'))

base/templates/base/footer.html
{% load static %}

<footer>
	<div class="container text-center">
		<ul class="list-inline">
			<li class="list-inline-item">
				<img src="{% static 'base/images/instagram.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
			<li class="list-inline-item">
				<img src="{% static 'base/images/twitter.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
			<li class="list-inline-item">
				<img src="{% static 'base/images/facebook.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
		</ul>

		<span id="footer-divider"></span>
		<p class="copyright">© 2019 pacility. | ALL RIGHTS RESERVED</p>
	</div>
</footer>

base/templates/base/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<title>{% block title %} {% endblock %} - pacility.</title>
		<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
		<script src="https://malsup.github.io/min/jquery.form.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<script src="{% static 'base/js/base.js' %}"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/base_style.css' %}">
		{% block link %} {% endblock %}
		<link href="https://fonts.googleapis.com/css?family=Raleway:400,500,800" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
		
	</head>

	<body>
		{% block body %}

		{% endblock %}
	</body>
</html>

base/templates/base/navbar.html
<nav class="navbar navbar-expand-sm sticky-top navbar-custom">
    <a class="navbar-brand" href="#">pacility.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav-content">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'homepage:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'report_form:report_form' %}">Form</a>
            <a class="nav-item nav-link" href="{% url 'report_list:report_list' %}">Reports</a>
            <a class="nav-item nav-link" href="{% url 'testimony:testimony' %}">Testimony</a>
            {% if user.is_authenticated %}
               <a class="nav-item nav-link nav-button" href="{% url 'logout' %}"><button class="btn btn-outline-secondary">Logout</button></a>
            {% else %}
                <button class="nav-item nav-link btn btn-outline-secondary" data-toggle="modal" data-target="#loginModal">Login</button>
            {% endif %}
        </div>
  </div>
</nav>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Login</h5>
            </div>

            <div class="modal-body">
                <div class="alert alert-danger" role="alert" >
                    Invalid username or password.
                </div>

                <form action="{% url 'login' %}" id="login-form">
                    <input type="hidden" id="csrf">{% csrf_token %}</input>
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" class="form-control" name="username" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" required>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Login">
                    </div>
                    <small class="form-text">Don't have an account? <a href="#loginModal" data-dismiss="modal" data-toggle="modal" data-target="#registerModal">Register</a></small>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Register</h5>
            </div>

            <div class="modal-body">
                <form action="{% url 'register' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>First Name</label>
                        <input type="text" class="form-control" name="first_name" required>
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        <input type="text" class="form-control" name="last_name" required>
                    </div>
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" class="form-control" name="username" required>
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" required>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Register">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>