base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('register', views.register, name='register'),
]

pacility/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('', include('homepage.urls')),
    path('report_form/', include('report_form.urls')),
    path('report_list/', include('report_list.urls')),
    path('testimony/', include('testimony.urls')),
]

report_form/urls.py
from django.urls import path
from . import views

app_name = 'report_form'

urlpatterns = [
	path('', views.add_report, name= 'report_form'),
	path('report_service/', views.add_report_service, name= 'add_report_service'),

]

report_form/models.py
from django.db import models

class Report(models.Model):
	form_title = models.CharField(max_length = 20)
	location = models.CharField(max_length = 20)
	time = models.TimeField()
	category = models.CharField(max_length = 20)
	description = models.TextField()

	def is_valid_report(self):
	    form_title_valid = len(self.form_title) > 0 and len(self.form_title) < 21
	    location_valid = len(self.location) > 0 and len(self.location) < 21
	    category_valid = len(self.category) > 0 and len(self.category) < 21
	    description_valid = len(self.description) > 0

	    return form_title_valid and location_valid and category_valid and description_valid

	# def __str__(self):
	#     return f"{self.time} - {self.form_title}"

report_form/forms.py
from django import forms
from . import models

class ReportForm(forms.ModelForm):
    form_title_attrs = {
        'placeholder' : 'Title',
        'class' : 'form-control',
    }
    location_attrs = {
        'placeholder' : 'Location',
        'class' : 'form-control',
    }
    time_attrs = {
        'type'  : 'time',
        'placeholder' : 'Time',
        'class' : 'form-control',
    }
    category_attrs = {
        'placeholder' : 'Category',
        'class' : 'form-control',
    }
    description_attrs = {
        'placeholder' : 'Write your description here...',
        'class' : 'form-control',
    }

    form_title = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = form_title_attrs))
    location = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = location_attrs))
    time = forms.TimeField(label= '',required=True, localize=True, widget = forms.TimeInput(attrs = time_attrs))
    category = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = category_attrs))
    description = forms.CharField(label = '', widget = forms.Textarea(attrs = description_attrs))


    class Meta:
        model = models.Report
        fields = ['form_title', 'location', 'time', 'category', 'description']

report_form/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .forms import ReportForm
from .models import Report
from datetime import datetime
from report_list.views import report_list
from .urls import *
import logging
import json

def index(request):
    logging.getLogger(__name__).debug("gagaggaa")
    form = ReportForm()
    reports = Report.objects.all()
    return render(request, 'report_form/report_form.html', {'form': form, 'reports': reports})

def add_report(request):
    # form = ReportForm()
    # reports = Report.objects.all()
    if(request.method == 'POST'):
        logging.getLogger(__name__).debug("gagaggaa")
        form = ReportForm(request.POST)
        # reports = Report.objects.all()
        if form.is_valid():
            
            new_form = form.save(commit=False)
            new_form.save()
            return redirect("report_list:report_list")
    else:
        form = ReportForm()
    return render(request, 'report_form/report_form.html', {'form': form, 'reports' : Report.objects.all()})

def add_report_service(request):
    if(request.method == 'POST'):
        logging.getLogger(__name__).debug("gagaggaa")
        form = ReportForm(request.POST)
        # reports = Report.objects.all()
        print(form.errors)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
            return JsonResponse({"status_code": 200, "message": "Report has been saved!"})
    else:
        return JsonResponse({"status_code": 200, "message": "Method /GET is not allowed"})

report_form/templates/report_form/report_form.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'report_form/css/form_style.css' %}">
{% endblock %}

{% block title %}
    Form
{% endblock %}

{% block body %}

{% include 'base/navbar.html' %}

{% if user.is_authenticated %} 
<style>
    details summary::-webkit-details-marker {
        display:none;
    }
</style>
<div class="content-div">
    <details ontoggle="myFunction()">
    <summary id="section-title" class="section-title" onmousedown="mouseDown()" onmouseup="mouseUp()" style="list-style: none;">REPORT FORM</summary>
    <p style= "font-family: Raleway;"> let us know your complaint</p>
    </details>
    <form action="{% url 'report_form:add_report_service' %}" method="POST" id="report_form-form">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.form_title }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.location }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.time }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.category }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-12">
                {{ form.description }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-12">
                <input class="form-group btn-submit float-right" value="Report" onclick="post_report()" style="width: 7.8%"; style="text-align: center;" >
            </div>
        </div>
    </form>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script>
        function mouseDown() {
            document.getElementById("section-title").style.color = "#F4976C"; 
            }

        function mouseUp() {
            document.getElementById("section-title").style.color = "#303C6C";
            }
        
        function myFunction() {
            }
            
        function post_report() {
            console.log("reportttt")
            data = {
                "csrfmiddlewaretoken": '{{ csrf_token }}',
                "form_title": document.getElementById("id_form_title").value,
                "location" : document.getElementById("id_location").value,
                "time": document.getElementById("id_time").value,
                "category": document.getElementById("id_category").value,
                "description": document.getElementById("id_description").value
            }
            $.ajax({
                type: "POST",
                url: "/report_form/report_service/",
                data: data,
                success: function( data, textStatus, jQxhr ){
                    if(!data["message"]) {
                        alert("EError, please check the fields");
                    } else {
                        alert(data["message"]);
                    }
                },
                error: function( jqXhr, textStatus, errorThrown ){
                    alert("Error, please check the fields");
                }
            });
        }
    </script>
</div>
{% else %}
   <div class= "row" style="width: 100vw; margin: 0;">
        <div class="col-md-12 authenReports">
        <h3 style="text-align: center;"></br></br></br></br></br>YOU HAVE TO LOGIN </br> TO FILL IN THE FORM</h3>
        </div>
   </div>
    {% endif %}

{% include 'base/footer.html' %}
{% endblock %}